Finish mobile version
Uthmanbello/setup-and-mobile pull request #2
Opened 2022-12-03 16:40 UTC by Uthmanbello

In this project:
1. I finished the mobile version of the portfolio
2. I used different styling methods

2022-12-03 16:54 UTC, ha-manel reviewed
# STATUS: INVALID 🔴 
Hi @Uthmanbello 
I'm sure you put a lot of effort into this project but this PR is invalid because you have failed linters checks 😓 

Kindly fix the issue and submit the PR for review again 👍 
Best of luck!

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 19:31 UTC, Owusu-Desmond requested changes
Hi @Uthmanbello , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the setup of the project ✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 19:31 UTC, Owusu-Desmond commented on index.html
> +            </div>
- [ ] Please make sure the list of project technologies (e.g., "JavasScript", "HTML" and "CSS") are a list `ul` and each of them a `li` :pray:

2022-12-03 19:31 UTC, Owusu-Desmond commented on index.html
> +            </div>
- [ ] Please make sure the list of project technologies (e.g., "JavasScript", "HTML" and "CSS") are a list `ul` and each of them a `li` :pray:

2022-12-03 19:31 UTC, Owusu-Desmond commented on index.html
> +            </div>
- [ ] Please make sure the list of project technologies (e.g., "JavasScript", "HTML" and "CSS") are a list `ul` and each of them a `li` :pray:

2022-12-03 19:31 UTC, Owusu-Desmond commented on index.html
> +            </div>
- [ ] Please make sure the list of project technologies (e.g., "JavasScript", "HTML" and "CSS") are a list `ul` and each of them a `li` :pray:

2022-12-03 19:31 UTC, Owusu-Desmond commented on styles.css
> +
- [ ] Please make the  `See project`  `button` follow the button styling: Active, Hover, and Pressed (see design)
![Screenshot from 2022-12-03 19-12-27](https://user-images.githubusercontent.com/92303891/205457943-227f0990-7771-43ac-9c9c-dc7f6cdd5c46.png)

2022-12-03 19:31 UTC, Owusu-Desmond commented on styles.css
> +  background: #ebebff;
- [ ] According to the [DRY (DO NOT REPEAT YOURSELF) ](https://vanseodesign.com/css/dry-principles/), we should not repeat a block of code with the same functionality. But as you can see the CSS properties in `back-link1`, `back-link2` and `back-link3` are the same except for the width. So why don't you give your elements with classes `back-link1`, `back-link2` and `back-link3` one class and use this class to style all of them? :smile: Then when you are done you can specify the width for each.

  **PLEASE MAKE SURE YOU DO THIS TO MAKE YOUR CODE CLEAN** :pray:

2022-12-03 19:31 UTC, Owusu-Desmond commented on index.html
> +    </footer>
- [ OPTIONAL ] Since this part is not the footer of the page, I recommended that you should use `div` tag instead of `footer` tag

2022-12-03 19:31 UTC, Owusu-Desmond commented on index.html
> +                <p class="head2">Tonic</p>
- [ ] Please make sure that the project title (e.g., "Tonic") uses a header tag `h2` or `h3` for semantic reasons :pray:

2022-12-03 19:31 UTC, Owusu-Desmond commented on index.html
> +                <p class="head2">Multi-Post Stories</p>
- [ ] Please make sure that the project title (e.g., "Tonic") uses a header tag `h2` or `h3` for semantic reasons :pray:

2022-12-03 19:31 UTC, Owusu-Desmond commented on index.html
> +                <p class="head2">Tonic</p>
- [ ] Please make sure that the project title (e.g., "Tonic") uses a header tag `h2` or `h3` for semantic reasons :pray:

2022-12-03 19:31 UTC, Owusu-Desmond commented on index.html
> +                <p class="head2">Multi-Post Stories</p>
- [ ] Please make sure that the project title (e.g., "Tonic") uses a header tag `h2` or `h3` for semantic reasons :pray:

2022-12-03 19:31 UTC, Owusu-Desmond commented on index.html
> +<h1 class="h">About <br>Myself</h1>
- [ ] Since `h1` is already used, Please make sure that you use any of the header tag `h2` or `h3` for semantic reasons :pray:

2022-12-03 21:01 UTC, Gambit142 reviewed
Hi @Uthmanbello 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that the linters checks failed. To fix te _**stylelint**_ errors, run this command `npx stylelint "**/*.{css,scss}" --fix`

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-04 01:31 UTC, Uthmanbello commented
The stylelint keeps failing even after everything has been corrected on my system here

2022-12-04 01:46 UTC, emmiiorji approved these changes
Hi @Uthmanbello, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Congrats](https://user-images.githubusercontent.com/20554583/205469960-e2cc5473-2aea-4ee8-9439-78a8c8607e09.gif)

## Good Highlights✔️

- Linter checks are passing
- Good commit messages
- Adhered to GitHub flow
- Required changes have been implemented

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-04 01:46 UTC, emmiiorji commented on test.md
> +
[Optional] In order to not have unused files, I recommend that you delete this file.

2022-12-06 08:44 UTC, merged