Contact
Uthmanbello/setup-and-mobile pull request #4
Opened 2022-12-06 22:51 UTC by Uthmanbello

In this project:
1. I made a form which submits to `formspree`
2. I made a name field for `Contact me` section
3. I made an email field
4. I made a message field

2022-12-06 23:39 UTC, abdulhamiid requested changes
Hi @Uthmanbello,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ 

- [ ] You have submitted a project with an empty pull request description. please let's provide a summary of the new changes in your pull request as a way to inform the reviewers of what we have worked on in the PR.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-07 00:56 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @Uthmanbello, 
![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️ Descriptions are very descriptive
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow
- ✔️ Meaningful commit messages.

## Required Changes ♻️
_Please kindly check the comments under the review._

### Your commit messages :point_down: 

![image](https://user-images.githubusercontent.com/78251927/206060658-d58efd70-9075-4c5b-bf5d-c537ec5aa248.png)

- [ ] As part of [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md), the commit message should be written in the imperative tense and capitalized, 

- [ ] Example :point_down: 

:x: Bad commit
```
make text field and email field form elements
```
:heavy_check_mark: Good commit
```
Make text field and email field form elements
```

- [ ] You used all the commit messages in small letters.
- [ ] 🏮 **IMPORTANT:** As it is not easy to change commit history, please kindly correct this behavior in the future.
- [ ]  You can learn more about **Professional repo - basic rules**  :point_right: [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-07 00:56 UTC, abdulhamiid commented on styles.css
- [ ] Please do not commit old pieces of code as inline comments. They will make your project look messy. If you need to review a previous version of your code, you can always use git history.

- [ ] Please kindly remove all the inline comments present in the CSS file 👍

2022-12-07 00:56 UTC, abdulhamiid commented on index.html
> +            </textarea></textarea>
Why is there another `text-area` field on line 240, was that a mistake 😀, please let's remove it to write clean code 👍

2022-12-07 00:56 UTC, abdulhamiid commented on index.html
> +        </form>
Please kindly include the button interactions such as hover, active (when it's pressed), disabled, and enable (default state) styles as shown in the Figma template as per [the project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/3_contact_form.md)

![image](https://user-images.githubusercontent.com/78251927/206054271-f0e3ceb4-e93e-464c-b8ed-86044ed5bf88.png)

2022-12-07 00:56 UTC, abdulhamiid commented on index.html
> +            <input type="email" class="email-txt email" placeholder="example@xyz.com" required />
- [ ] The form submission is not working properly, I got this error message by submitting the form 👇 , let's fix it

![image](https://user-images.githubusercontent.com/78251927/206052656-b979e388-82da-49c4-aaba-657a56b7fbb3.png)

- [ ] The error message was that you didn't specify a "name" attribute in all your form elements. The HTML <form> name attribute is used to specify the name of a form Element. It is used to reference the form-data after submitting the form or to reference the element in JavaScript. 

### Syntax
```
<input name="first-name" type="text" value="Chhabra">
```

Your design 👇 
![image](https://user-images.githubusercontent.com/78251927/206058797-cb202297-4f34-4636-939d-5714086cbd6b.png)

Figma design 👇 
![image](https://user-images.githubusercontent.com/78251927/206059139-5a9d5f97-16c8-477f-aeec-ff6d597da825.png)

As it was stated in the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/3_contact_form.md) we must stick to the design as much as possible (e.g., font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

Please consider fixing the left and right margins of the section as shown above to place the contents in the center, so that your design will match the provided Figma template.

Also, please kindly remove the white space on the left side of your design to match the Figma design.

2022-12-07 14:45 UTC, ha-manel approved these changes
# STATUS: APPROVED ✅

## Hi Team👋

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: 
**Congratulations! 🎉**

<img src="https://media3.giphy.com/media/l4JySAWfMaY7w88sU/giphy.gif"/>

## Highlights:
* Well written PR description ✔️ 
* All tests passed ✔️ 

## Optional suggestions:
- [ ] It's better if the website takes the full width of the screen instead of a portion of it because in mobile it becomes too small and almost not readable and visible 👍 


------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-07 15:03 UTC, Uthmanbello commented
Thanks a lo

2022-12-07 15:03 UTC, merged